name: raychat
description: A reactive chat application fueled by a Firebase Realtime Database.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  provider: ^6.0.3
  firebase_auth:  ^4.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
